### ISSUE TITLE
error instalation on Linux Mint

### ISSUE THREAD

**Issue by vgarciacastro** [imirzov/Install-Abaqus-2019-on-Ubuntu-18.04-LTS#1]
Hi, I don't know if I am doing well. I have try to install Abaqus (Simulia 2021) on Linux Mint 20, and I get the below error

//Abaqus/1/inst/linux_a64/code/bin/DSYInsAppliGUI: symbol lookup error: //Abaqus/1/inst/linux_a64/code/bin/DSYInsAppliGUI: undefined symbol: u_strToLower_50

Can you help me?

**Comment by imirzov** [comment]
Sorry, no. Have no idea what can be the reason for this error.
I do not have Linux Mint and Abaqus 2021.
